version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.production
    ports: 
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  api:
    depends_on:
      - mongo
    env_file:
      - .env.production
    image: habit-tracker-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes: 
      - ./server:/app
  nginx: 
    depends_on:
      - api
    env_file:
      - .env.production
    image: nginx
    ports: 
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${NGINX_SSL_PORT}:${NGINX_SSL_PORT}
    volumes:
      - ./conf/nginx:/etc/nginx/templates
      - ./conf/certbot/www:/var/www/certbot/:ro
      - ./conf/certbot/conf/:/etc/nginx/certs/:ro
  certbot:
    env_file:
      - .env.production
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www/:/var/www/certbot/:rw
      - ./data/certbot/conf/:/etc/letsencrypt/:rw
