version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env.production
  api:
    depends_on:
      - mongo
    env_file:
      - .env.production
    image: habit-tracker-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${NODE_PORT}:${NODE_PORT}
