name: scp files
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bucket actions
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Build client
      working-directory: './client'
      run: | 
        npm install
        npm run build
    - name: Publish client
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY}}
        port: ${{ secrets.PORT }}
        overwrite: true
        source: "./client/build/*"
        target: "~/apps/habit-tracker-client"
